### ISSUE TITLE
.build() vs .run()

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive#16]
Currently, `PublisherBuilder`, `SubscriberBuilder` and `ProcessorBuilder` have a `.build()` method, while `CompletionBuilder` has a `.run()` method. Should we change `CompletionBuilder` to use `.build()`? Consistency would be good, and also it makes sense because it's a builder so it should have a build method, but, at the same time, unlike the other builders, when you build a `CompletionBuilder`, it actually runs the stream. Another possibility could be to change the name of `CompletionBuilder`, maybe to `RunnableStream` or something like that, then it can have a `run()` method, since you can't actually do any more operations or builder methods on a `CompletionBuilder` anyway.

**Comment by viktorklang** [comment]
@jroper Perhaps decouple build() from run() (one could imagine the build()-step doing optimizations etc. whereas the run()-step actually runs it)

**Comment by jroper** [comment]
The problem is, from an end user API perspective, that would mean having to execute `.build().run()`. I don't think it would ever be useful to invoke `.build()` without invoking `.run()`, so while separating them might make sense internally, it's just going to add more boiler plate for end users for no value to them.

**Comment by cescoffier** [comment]
It's been discussed during the MicroProfile Reactive call (July 3rd). We decided to rename `CompletionBuilder` to `CompletionRunner` and keep the `run` method.
