### ISSUE TITLE
Naming inconsistencies inherrited from Java 8 stream

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive#33]
From @venkats:

> I truly do not like how the (Java 8) Stream API has been inconsistent in naming. For example, `limit`, but `takeWhile`, and `skip` but `dropWhile`. I encourage the API used in the Builders to be more consistent. For example, it may be better to either use `limit` and `limitWhile` or `take` and `takeWhile`.

**Comment by jroper** [comment]
I don't have a particularly strong opinion here - it seems like a choice between two evils, inconsistency with naming already used in the JDK, or internal inconsistency in its own API. The latter is possibly worse, so it may be a good idea to consider this.

**Comment by cescoffier** [comment]
I don't have a strong opinion either as soon as the differences (mapping) are documented in the spec. Do you want me to proceed?

**Comment by Emily-Jiang** [comment]
Keep them consistent is a good thing.
