### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive#4]
We need to setup CI on this repo. I'm not sure what's required for that.

**Comment by Emily-Jiang** [comment]
what do you need for CI? Is the existing infra not sufficient?

**Comment by jroper** [comment]
I basically need someone to either set it up or show me how it's done, currently I have no idea what infrastructure exists or how to access it.

**Comment by jroper** [comment]
I understand that there is a CI server set up, but when I submit a pull request to this repository, to my knowledge, no jobs are run to verify it. Presumably, something needs to be configured so that that happens?

**Comment by jroper** [comment]
Specifically, here's the MicroProfile CI server:

https://hudson.eclipse.org/microprofile/

I don't see any jobs there configured for microprofile-reactive. Who should I talk to about getting that configured? Also I just had a look across a few MicroProfile projects, I see that none are actually using PR validation (ie, something that builds a PR before it gets merged, to validate that it compiles). Is this something we can set up?

**Comment by Emily-Jiang** [comment]
I see. There is no CI set up for PR. Normally running `mvn clean install`

**Comment by jroper** [comment]
CI is now setup.
