### ISSUE TITLE
Should `flatMap` also support receiving a `Publisher`

### ISSUE THREAD

**Issue by cescoffier** [eclipse/microprofile-reactive#49]
In the current version, the `flatMap` operator accept a method returning the `PublisherBuilder`. What about also being able to return a `Publisher` directly.

While I agree we can always use `ReactiveStreams.fromPublisher(actualPublisher)`, it could be simplified. 

Obviously, because of Java limitation on generics, this new operator should be named differently, `flatMapPublisher` maybe.

**Comment by jroper** [comment]
I have no objections to this.

**Comment by cescoffier** [comment]
Ok, I will open a PR Today.

**Comment by cescoffier** [comment]
PR opened: #50
