### ISSUE TITLE
Alternative names for SubscriberWithResult

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive#5]
[`SubscriberWithResult`](https://github.com/eclipse/microprofile-reactive/blob/8afc496c8e0c724db2a063e1662228de3c090dd1/streams/api/src/main/java/org/eclipse/microprofile/reactive/streams/SubscriberWithResult.java) is a product of a reactive stream `Subscriber` and a `CompletionStage`. It is used to hold both the thing that consumes a stream, as well as the result of consuming that stream, whether that result is a reduction of the elements of the stream, or in some cases the result has no value (is `Void`), but the `CompletionStage` indicates whether the stream completed normally or with an error.

I don't particularly like the name, it adequately describes what it is to be sure, but it's long. Here are some alternatives that I've thought of:

* `Accumulator` - essentially, the `Subscriber` is responsible for accumulating a value into `CompletionStage`. We use this name in [Play Framework](https://www.playframework.com/documentation/2.6.x/api/java/play/libs/streams/Accumulator.html) for a somewhat similar abstraction. Some potential issues with this name - for cases where there's no result value (ie `Void`), the name isn't very intuitive. Also the term `Accumulator` is already used in the JDK in [`LongAccumulator`](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/atomic/LongAccumulator.html) and [`DoubleAccumulator`](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/atomic/DoubleAccumulator.html).
* `SubscriberResult` - a shortening of `SubscriberWithResult`

Any other ideas?

**Comment by hutchig** [comment]
I think both SubscriberWithResult and Accumulator are 'good enough'. I slightly
prefer SubscriberWithResult...as there is no way of getting at anything accumulated
until the stream completes. 

Keep thinking of 'FluxToMono' but that
is because I am just injesting a lot of reactive material from lots of sources.
StreamToCompletionStage is a bit of a mouthful of its own
and this is just for a particular Subscriber.

My second favourite option (over how it is) is that
I would be tempted to call the class's methods:
 
getRsSubscriber->getSubscriber and
getResult->getCompletionStage.  

and then the class would be SubscriberWithCompletionStage but that is  too long
so I prefer what you have now.

**Comment by viktorklang** [comment]
`CompletingSubscriber`?

**Comment by hutchig** [comment]
I spotted in the Builder name that a CompletionStage is referred to as a Completion (CompletionBuilder). To be consistent here I would replace "Result" with Comopletion
if that shortening is used elsewhere - otherwise there are two short forms/nicknames for
CompletionStage - 'Result' and 'Completion'

**Comment by jroper** [comment]
Re: `CompletingSubscriber` - it makes it sound like this a subscriber with a particular property (it completes, which doesn't really make sense). `SubscriberCompletion` sounds a little better because it's a subscriber that also captures completion. `CompletionSubscriber` might even work, `CompletionStage` is a stage that asynchronously produces a value on complete, `CompletionSubscriber` is a subscriber that produces an asynchronously produces a value on complete - it's a weird name but no weirder than `CompletionStage`, and possibly consistent with the naming of `CompletionStage`.

@hutchig I think it's good you raise the naming of `CompletionBuilder` because that also deserves a decent round of iteration on. The naming of it as it stands is a little weird (though perhaps not as weird if we rename `SubscribeWithResult` to `CompletionSubscriber`. It could also be called a `ClosedGraphBuilder`, the main reason why I didn't go with that is that what is being built is a `CompletionStage`, and that introduces a new terminology into the API that until that point wasn't needed.

**Comment by jroper** [comment]
One possibility that we could investigate is whether `SubscriberWithResult` should have a `Subscriber`, or if it should instead implement `Subscriber`. If we renamed it to `CompletionSubscriber`, then implementing `Subscriber` might make sense. We could even make it implement both `CompletionStage` and `Subscriber` - as long as `CompletionStage` never adds `onError/onComplete` methods itself (these methods are not consistent with the naming strategy it already uses, so probably no problems there).

Since this API only ever returns a `SubscriberWithResult`, I think it's not too bad a thing to extend them, however extending them can introduce confusion as it can encourage people to implement their own. We would probably want to provide some static utility methods to allow the creation of a new one from a `Subscriber` and a `CompletionStage`.

**Comment by jroper** [comment]
What do people think of `CompletionSubscriber`? Should I create a PR to see what it looks like?

**Comment by ederks85** [comment]
I have given it some thought as well and I think this is a suitable name. The Completion part implies that it accumulates until a completion (done or error), and that it subscribes to start doing just that.

So I guess we don't need an expliciet AccumulatingCompletingSubscriber ;)

**Comment by viktorklang** [comment]
CompletionSubscriber sounds good to me

**Comment by hutchig** [comment]
Sounds good to me.

**Comment by Emily-Jiang** [comment]
CompletionSubscriber sounds a bit odd. How about Subscription, which is the subscriber with result?

**Comment by jroper** [comment]
`Subscription` already exists in Reactive Streams:

https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.Subscription.html

And it means something different, calling it `Subscription` would confuse things there.
