### ISSUE TITLE
Can @Outgoing be @Named?

### ISSUE THREAD

**Issue by cescoffier** [eclipse/microprofile-reactive#73]
Methods annotated with `@Ougtoing` method can be also annotated with `@Named` so other method using `@Incoming` should be able to retrieve them.

Example:

```
@Incoming(topic = "my-stream")
@Named("toUpperCase")
public Publisher<String> toUppercase(Flowable<String> input) {
    return input.map(String::toUpperCase);
}

// ....
@Incoming(topic = "toUpperCase")
@Outgoing(topic = "my-output")
public PublisherBuilder<String> duplicate(PublisherBuilder<String> input) {
    return input.flatMap(s -> ReactiveStreams.of(s, s));
}
```

**Comment by jroper** [comment]
I'm not sure, it feels like an overloading of `@Named` that it wasn't meant to have. My concern is that it would add too many different ways of achieving the same thing.

My thoughts is that if we wanted internal plumbing without a message broker, we should use CDI events, eg:

```java
@Incoming(topic = "my-stream")
@Outgoing(provider = CDIMessagingProvider.class)
public Publisher<String> toUppercase(Flowable<String> input) {
    return input.map(String::toUpperCase);
}

@Incoming(provider = CDIMessagingProvider.class)
@Outgoing(topic = "my-output")
public PublisherBuilder<String> duplicate(PublisherBuilder<String> input) {
    return input.flatMap(s -> ReactiveStreams.of(s, s));
}
```

In this case, it would use a CDI events publisher/observer of `String`. We could also combine it with qualifiers such as `@Named` (though, how would we define whether it was for the incoming or outgoing?) to qualify the events.

**Comment by cescoffier** [comment]
If we switch `topic` to `name`, `@Named` is not required anymore - as the name is indicated in the `@Incoming` and `@Outgoing` annotations.
