### ISSUE TITLE
Stream splitting

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive#9]
We might want to introduce some stream splitting functions. For example, a `splitWhen` function.

This functionality is generally only useful when doing parsing, where you parse some sort of header out of the stream, followed by a sub stream, then another header, etc.

Generally, the element that is split at needs to be accessed before consuming the sub stream. So the sub stream should make that element available, along with the rest of the stream. For example:

```java
PublisherBuilder<SubStream<T>> splitWhen(Predicate<? super T> predicate);
class SubStream<T> {
  final T first;
  final PublisherBuilder<T> rest;
}
```

So, for each element where the predicate holds `true` (including the first element of the stream regardless of whether the predicate holds true or not), a `SubStream` is emitted, with `first` being that element, and `rest` being the remainder of the stream as long as the predicate holds `false`.

**Comment by hutchig** [comment]
Would it be sensible to just to port everything at https://doc.akka.io/docs/akka/2.5/stream/stream-substream.html ?  Or have a roadmap where we plan to import all the stream 'functions' from another, more mature environment but in a sensible order?
Akka, Reactor etc?
This might be less of a 'cognitive load' that digesting functions one at a time - when they exist as part of a n'th generation set and are 'mature' in other contexts?

**Comment by jroper** [comment]
We certainly could port everything there, however there's definitely no agreement into what kind of scope "there" should have between the libraries out there.

I think we need to consider use cases that we want to support. The reason why I raised this specific operator is that when I was implementing a Reactive Streams based multipart/form-data handler for a proposal for the Servlet API, this is one of the operators that was needed to implement that. Based on that, I envision that generally, this will be a very useful operator for anything that does parsing or implements any sort of streaming protocols. However, perhaps that's beyond the scope of where we expect this API to be used, if we're primarily expecting it to be used for messaging, for example, then parsing/protocol implementation is not such a big concern.

**Comment by hutchig** [comment]
Building up operators on use case/need is a good approach.

In terms of terminology, it is a shame that RxJava/Reactor/Akka are all different names
but I trust your judgement/experience on the naming.

**Comment by jroper** [comment]
Don't trust my judgement, question it :)

One thing that probably deserves another issue is there are two different ways you consume the resulting streams from a flatMap, you can either merge them, or you can concatenate them. I've tried to simplify things because generally I only see a need for concatenating, and so all the flatMaps are just doing a concatenate. But not everyone would share that opinion. We may need to introduce a `flatMapMerge` and `flatMapConcat`, and once again, there are multiple different strategies for naming these.

**Comment by Emily-Jiang** [comment]
What is your use case here? What problem are you trying to solve?

**Comment by jroper** [comment]
As discussed in the Reactive weekly hangout, while this is useful functionality, for the first iteration of the API we want to keep the scope limited, and we've decided that that should be limited to just use cases that are useful for the messaging spec. So I'm going to close this issue for now, we can revisit later, especially if this spec gets adopted in other places where parsing/protocol implementation may be an interesting thing to do.
